### ISSUE TITLE
Issues installing with Django/Wagtail

### ISSUE THREAD

**Issue by the-moog** [jazzband/django-invitations#127]
May be a documentation issue?

Trying to install invitations into a Wagtail install.

Adding invitations to urls and INSTALLED_APPS results in:
    RuntimeError: Model class django.controb.sites.models.Site doesn't declare an explicit app_label and isn't an application in INSTALLED_APPS.

Adding django.contrib.sites seems to fix this

**Comment by valberg** [comment]
Yes it does! We've written this in the readme in https://github.com/jazzband/django-invitations/commit/b6ae99e4dc90ff8d1fa1aac233b67836de50b3a9
