### ISSUE TITLE
Send invitation error if no SITE_ID defined

### ISSUE THREAD

**Issue by mitzitjin** [jazzband/django-invitations#130]
When you do not have a SITE_ID defined, send_invitation fails on getting the current site. You can easily fix this by adding this line in the send_invitation method:

current_site = kwargs.pop('site', Site.objects.get_current(request))

**Comment by valberg** [comment]
Fixed in https://github.com/jazzband/django-invitations/commit/b6ae99e4dc90ff8d1fa1aac233b67836de50b3a9
