### ISSUE TITLE
Django invitations giving error This chandansblog.pythonanywhere.com page can’t be foundThis page may have been moved or deleted. HTTP ERROR 410

### ISSUE THREAD

**Issue by chandan315** [jazzband/django-invitations#164]
I have setup my django app on pythonanywhere.com

I have installed django-invitations module and I am able to create my invitations from admin backend.

The problem is when I recieve my mail and the link to my site, I get the following error:

This chandansblog.pythonanywhere.com page can’t be foundThis page may have been moved or deleted. HTTP ERROR 410

It works locally fine, but not on the server.

What is the problem?

**Comment by valberg** [comment]
Hi @chandan315

This sounds like a problem with your setup at pythonanywhere.com.

I'm closing this issue. If you think it is still related to django-invitations feel free to reopen :)
