### ISSUE TITLE
Indicate which Django versions are supported

### ISSUE THREAD

**Issue by brylie** [jazzband/django-invitations#167]
The `django-invitations` [package on PyPI](https://pypi.org/project/django-invitations/) doesn't currently indicate which versions of Django are supported. Please configure the project to indicate which Django versions are supported.

**Comment by shawnngtq** [comment]
@brylie , so, do you know which versions are support? 😁

**Comment by brylie** [comment]
Not sure, but I'd say stick with Django 3.2.x LTS

**Comment by marcosmoyano** [comment]
Just confirmed that Django 4 is not supported 😬
