### ISSUE TITLE
Update translation deprecations

### ISSUE THREAD

**Issue by macmichael01** [jazzband/django-invitations#171]
Django has deprecated ugettext in Django 3 and is removed in Django 4

RemovedInDjango40Warning:
django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext()

Old
~~~python
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as _
~~~

New
~~~python
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext as _
~~~

Consider adding compatibility.

**Comment by valberg** [comment]
Fixed in https://github.com/jazzband/django-invitations/pull/169
