### ISSUE TITLE
Pre-commit hooks failing

### ISSUE THREAD

**Issue by brylie** [jazzband/django-invitations#196]
Our Pre-Commit CI service is throwing errors about some of the hooks.

## Task

- [ ] fix code errors related to pre-commit

**Comment by brylie** [comment]
@jezdez, I'd like to include these fixes in the next release, since they are automated.

**Comment by jezdez** [comment]
Totally, since no release happened to PyPI, it's easy to include it. Just make sure to delete the 2.0.0 tag/release here again.
