### ISSUE TITLE
Consider adding default_auto_field to AppConfig

### ISSUE THREAD

**Issue by amartinezuy** [jazzband/django-invitations#202]
Hello,

Starting with [Django 3.2](https://docs.djangoproject.com/en/4.1/releases/3.2/), newly created projects will include the following line in `settings.py`:

```python
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
```

When installing `django-invitations` in such a context and running `python manage.py migrate` we get the following message:

>Your models in app(s): 'invitations' have changes that are not yet reflected in a migration, and so won't be applied.
> Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

And running `makemigrations` would create a migration like this:

```python
operations = [
    migrations.AlterField(
        model_name='invitation',
        name='id',
        field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    ),
]
```

But, naturally, this migration would be created in the packages installation directory (usually a virtualenv). Which is undesirable behavior.

There are ways to patch this from outside the lib, but maybe it would be a good idea to modify [`invitations/apps.py`](https://github.com/jazzband/django-invitations/blob/master/invitations/apps.py) to look like this:

```python
from django.apps import AppConfig


class Config(AppConfig):
    """Config."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = "invitations"
    label = "invitations"
```

**Comment by valberg** [comment]
Fixed in https://github.com/jazzband/django-invitations/commit/7707f545270f58eeb8a4d2e61872dfbdeecc56fd
