### ISSUE TITLE
send-invite/ and send-json-invite/

### ISSUE THREAD

**Issue by xMrAli** [jazzband/django-invitations#210]
Hi

I am new to coding

i was trying to figure out how to do Bulk Invites Via JSON same as #125 , But the docs are extremely short.

Any way i found this link `send-invite/ ` in the `'invitations.urls'`  it's works in the front-end.

also found this link `send-json-invite/` but i don't know how to use it. 

Can the maintainer add feature upload JSON file in the Admin Area?

Many thanks
Ali

**Comment by valberg** [comment]
Looking at the test which tests the JSON bulk inviting might help: https://github.com/jazzband/django-invitations/blob/master/tests/basic/tests.py#L427
