### ISSUE TITLE
Improve the documentation for the configuration of the app

### ISSUE THREAD

**Issue by kaiserls** [jazzband/django-invitations#218]
I think it would be very helpful to have an example how to set up django-invitations with a custom user model.
https://django-invitations.readthedocs.io/en/latest/configuration.html

I can't provide a pull request because I didn't manage to get it running.

**Comment by valberg** [comment]
Hi @kaiserls - did you follow the installation instructions? https://django-invitations.readthedocs.io/en/latest/installation.html

**Comment by kaiserls** [comment]
Yes, however I struggled with configuring the custom user model with django-invitations and including it in the admin panel.

**Comment by Flimm** [comment]
It's not clear what issues you are running into. Could you clarify this, and reopen this issue?
