### ISSUE TITLE
Bug: On localhost port is not included in the accept-invite URL

### ISSUE THREAD

**Issue by Huge** [jazzband/django-invitations#245]
Mails have links like 
http://localhost/invitations/accept-invite/y2g3lqnftohfwhismsuq9ecdaitmbcggequqmgfdu0zricyitjokslnpbxjzkcoz

instead of 
http://localhost:8000/invitations/accept-invite/y2g3lqnftohfwhismsuq9ecdaitmbcggequqmgfdu0zricyitjokslnpbxjzkcoz

**Comment by nebiyuelias1** [comment]
But this is what I'm getting instead:
`If you'd like to join, please go to http://localhost:8000/invitations/accept-invite/9ary1xawihqhqykgwgpkpqmtjqqau8dmvil4m0pdulrbxkh4cbwbr31ztz1kvdeg`
Can you please provide the steps you used?

**Comment by Huge** [comment]
Oh, damn, it seems I was missing this line in my `settings.py`:
`    SITE_URL = f'http://localhost:8000'`
