### ISSUE TITLE
InvitationAdminAddForm could be improved by adding dropdown instead of integer field for inviter

### ISSUE THREAD

**Issue by JoGorska** [jazzband/django-invitations#259]
To create a new invitation in the admin field a user ID needs to be used as an inviter. It would be much more practical to use `forms.ModelChoiceField` instead and have a full dropdown of all users. 

Alternatively, it might be worth considering adding an initial value from `request.user.id`.

![Screenshot from 2024-08-08 07-42-31](https://github.com/user-attachments/assets/bfc3fb51-7b7c-48ab-9fe2-951bc51a45e8)

**Comment by Flimm** [comment]
Since there may be a large number of users, a dropdown could be unusable. It might be better to use an [autocomplete  field](https://docs.djangoproject.com/en/stable/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields). Pull requests welcome.
