### ISSUE TITLE
validate_invitation being called twice when sending an invite?

### ISSUE THREAD

**Issue by john2x** [jazzband/django-invitations#39]
I'm getting two messages when sending a new invite:

```
This e-mail address has already been invited
foo@example.com has been invited
```

It seems that `validate_invitation` is being called twice.

I did some debugging, and noticed that the following line in the `SendInvite` view somehow causes it to be called twice:

```
return self.render_to_response(
            self.get_context_data(
                success_message='%s has been invited' % email))
```

Calling `self.get_context_data` alone doesn't trigger the bug. Only when passing the returned value of `self.get_context_data` to `self.render_to_response` causes it.

Changing it to:

```
return self.render_to_response({
    'form': form,
    'success_message': '%s has been invited' % email
})
```

seems to fix the bug.

EDIT: using Django 1.9.5

**Comment by bee-keeper** [comment]
Thanks for reporting this.  I'll look into it as soon as I get a chance.

**Comment by valberg** [comment]
I'm closing this due to the age of the issue.
